name: easy_money_formatter
description: A Dart package to format numbers into money-friendly representations.
version: 1.0.2
repository: https://github.com/AppFusion-boop/easy_money_formatter
homepage: https://github.com/AppFusion-boop/easy_money_formatter

environment:
  sdk: ">=3.5.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
